// Generates 07c-geo-data.js: simplified land outlines + country/US-state centroids
// for the built-in Overview globe. Inputs (npm, offline-safe once fetched):
//   world-atlas@2 (Natural Earth 1:110m land, 1:50m countries; public domain data)
//   world-countries@5 (ISO 3166 code <-> name mapping only; ODbL, credited)
// Usage: node build-geo.mjs <world-atlas/package> <world-countries/package> > ../07c-geo-data.js
import fs from 'node:fs';
const [, , WA, WC] = process.argv;
const topo = f => JSON.parse(fs.readFileSync(`${WA}/${f}`, 'utf8'));
function decodeArcs(t) {
  const [sx, sy] = t.transform.scale, [tx, ty] = t.transform.translate;
  return t.arcs.map(a => { let x = 0, y = 0; return a.map(([dx, dy]) => { x += dx; y += dy; return [x * sx + tx, y * sy + ty]; }); });
}
function ringFrom(arcs, idxs) {
  const out = [];
  idxs.forEach(i => { const a = i < 0 ? arcs[~i].slice().reverse() : arcs[i]; a.forEach((p, k) => { if (k || !out.length) out.push(p); }); });
  return out;
}
function polys(geom, arcs) {
  if (geom.type === 'Polygon') return [geom.arcs.map(r => ringFrom(arcs, r))];
  if (geom.type === 'MultiPolygon') return geom.arcs.map(p => p.map(r => ringFrom(arcs, r)));
  return [];
}
// Land outlines (1:110m), outer rings only, rounded to 0.1 degree, light decimation.
const land = topo('land-110m.json'); const la = decodeArcs(land);
const rings = [];
land.objects.land.geometries.forEach(g => polys(g, la).forEach(p => {
  const r = p[0]; const o = []; let last = null;
  r.forEach(([x, y]) => { const q = [Math.round(x * 10), Math.round(y * 10)]; if (!last || Math.abs(q[0] - last[0]) + Math.abs(q[1] - last[1]) >= 4) { o.push(q); last = q; } });
  if (o.length >= 4) rings.push(o);
}));
// Delta-encode each ring: "x0,y0,dx,dy,dx,dy..."
const LAND = rings.map(r => { const out = [r[0][0], r[0][1]]; for (let i = 1; i < r.length; i++) out.push(r[i][0] - r[i - 1][0], r[i][1] - r[i - 1][1]); return out.join(','); });
// Country centroids from 1:50m countries: area-weighted centroid of the largest polygon.
const cty = topo('countries-50m.json'); const ca = decodeArcs(cty);
function ringArea(r) { let a = 0, cx = 0, cy = 0; for (let i = 0, j = r.length - 1; i < r.length; j = i++) { const f = r[j][0] * r[i][1] - r[i][0] * r[j][1]; a += f; cx += (r[j][0] + r[i][0]) * f; cy += (r[j][1] + r[i][1]) * f; } a /= 2; return a ? { a: Math.abs(a), x: cx / (6 * a), y: cy / (6 * a) } : { a: 0, x: r[0][0], y: r[0][1] }; }
const wc = JSON.parse(fs.readFileSync(`${WC}/countries.json`, 'utf8'));
const byN = new Map(wc.map(c => [String(c.ccn3).padStart(3, '0'), c]));
const COUNTRIES = [];
cty.objects.countries.geometries.forEach(g => {
  const ps = polys(g, ca); if (!ps.length) return;
  let best = null; ps.forEach(p => { const k = ringArea(p[0]); if (!best || k.a > best.a) best = k; });
  const w = byN.get(String(g.id).padStart(3, '0'));
  const names = new Set([g.properties.name]); if (w) { names.add(w.name.common); names.add(w.name.official); (w.altSpellings || []).forEach(s => { if (s.length > 3) names.add(s); }); }
  COUNTRIES.push([w ? w.cca2 : '', Math.round(best.y * 100) / 100, Math.round(best.x * 100) / 100, Array.from(names).join('|')]);
});
// Small territories missing from 1:50m polygons but common in trial/recall records.
[['SG', 1.35, 103.82, 'Singapore'], ['HK', 22.32, 114.17, 'Hong Kong|Hong Kong SAR'], ['MO', 22.2, 113.55, 'Macao|Macau'], ['MT', 35.9, 14.45, 'Malta'], ['BH', 26.07, 50.55, 'Bahrain'], ['LU', 49.82, 6.13, 'Luxembourg'], ['MC', 43.74, 7.42, 'Monaco']].forEach(x => { if (!COUNTRIES.some(c => c[0] === x[0])) COUNTRIES.push(x); });
const js = `/* ====================================================================
   GEO DATA (generated by tools/build-geo.mjs; do not edit by hand)
   Land outlines: Natural Earth 1:110m (public domain) via world-atlas.
   Country centroids: computed from Natural Earth 1:50m polygons.
   ISO 3166 code/name mapping: mledoze/countries (ODbL 1.0), credited in
   Sources & Privacy > Technical credits. Used only to place public,
   non-PHI location records; never device location.
   ==================================================================== */
var GEO_LAND = ${JSON.stringify(LAND)};
var GEO_COUNTRIES = ${JSON.stringify(COUNTRIES)};
`;
process.stdout.write(js);
